### ISSUE TITLE
/masterclasses is returning 5xx responses

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/webteam.canonical.com#122]
Trying to visit that page results in either 502 Bad Gateway, or a 500:

![image](https://user-images.githubusercontent.com/2376968/175051266-f2eebae4-05f7-46c5-9abd-a414d8449feb.png)

**Comment by anthonydillon** [comment]
I am confused by this one. At first, I thought it would be secrets but turns out it might be to do with sheet permissions. Needs further investigation.

**Comment by anthonydillon** [comment]
@andesol DM'ed you.

**Comment by anthonydillon** [comment]
Great spot Goulin. Well done! :+1:
